// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change INC rr + DEC rr  .tt instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        /// <summary>
        /// The INC BC instruction.
        /// </summary>
        byte INC_BC()
        {
            FetchFinished();
            Registers.BC = Registers.BC.Inc();
            return 6;
        }

        /// <summary>
        /// The DEC BC instruction.
        /// </summary>
        byte DEC_BC()
        {
            FetchFinished();
            Registers.BC = Registers.BC.Dec();
            return 6;
        }

        /// <summary>
        /// The INC DE instruction.
        /// </summary>
        byte INC_DE()
        {
            FetchFinished();
            Registers.DE = Registers.DE.Inc();
            return 6;
        }

        /// <summary>
        /// The DEC DE instruction.
        /// </summary>
        byte DEC_DE()
        {
            FetchFinished();
            Registers.DE = Registers.DE.Dec();
            return 6;
        }

        /// <summary>
        /// The INC HL instruction.
        /// </summary>
        byte INC_HL()
        {
            FetchFinished();
            Registers.HL = Registers.HL.Inc();
            return 6;
        }

        /// <summary>
        /// The DEC HL instruction.
        /// </summary>
        byte DEC_HL()
        {
            FetchFinished();
            Registers.HL = Registers.HL.Dec();
            return 6;
        }

        /// <summary>
        /// The INC SP instruction.
        /// </summary>
        byte INC_SP()
        {
            FetchFinished();
            Registers.SP = Registers.SP.Inc();
            return 6;
        }

        /// <summary>
        /// The DEC SP instruction.
        /// </summary>
        byte DEC_SP()
        {
            FetchFinished();
            Registers.SP = Registers.SP.Dec();
            return 6;
        }

        /// <summary>
        /// The INC IX instruction.
        /// </summary>
        byte INC_IX()
        {
            FetchFinished();
            Registers.IX = Registers.IX.Inc();
            return 10;
        }

        /// <summary>
        /// The DEC IX instruction.
        /// </summary>
        byte DEC_IX()
        {
            FetchFinished();
            Registers.IX = Registers.IX.Dec();
            return 10;
        }

        /// <summary>
        /// The INC IY instruction.
        /// </summary>
        byte INC_IY()
        {
            FetchFinished();
            Registers.IY = Registers.IY.Inc();
            return 10;
        }

        /// <summary>
        /// The DEC IY instruction.
        /// </summary>
        byte DEC_IY()
        {
            FetchFinished();
            Registers.IY = Registers.IY.Dec();
            return 10;
        }

    }
}
