
// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "INI +             .tt" instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        /// <summary>
        /// The INI instruction.
        /// </summary>
        byte INI()
        {
            FetchFinished();

            var portNumber = Registers.C;
            var address = Registers.HL;
            var value = ProcessorAgent.ReadFromPort(portNumber);
            ProcessorAgent.WriteToMemory((ushort)address, value);

            Registers.HL++;
            var counter = Registers.B;
            counter = (byte)(counter - 1);
            Registers.B = counter;
            Registers.ZF = (counter == 0);
            Registers.NF = 1;
            Registers.SF = counter.GetBit(7);
            SetFlags3and5From(counter);


            return 16;
        }

        /// <summary>
        /// The IND instruction.
        /// </summary>
        byte IND()
        {
            FetchFinished();

            var portNumber = Registers.C;
            var address = Registers.HL;
            var value = ProcessorAgent.ReadFromPort(portNumber);
            ProcessorAgent.WriteToMemory((ushort)address, value);

            Registers.HL--;
            var counter = Registers.B;
            counter = (byte)(counter - 1);
            Registers.B = counter;
            Registers.ZF = (counter == 0);
            Registers.NF = 1;
            Registers.SF = counter.GetBit(7);
            SetFlags3and5From(counter);


            return 16;
        }

        /// <summary>
        /// The INIR instruction.
        /// </summary>
        byte INIR()
        {
            FetchFinished();

            var portNumber = Registers.C;
            var address = Registers.HL;
            var value = ProcessorAgent.ReadFromPort(portNumber);
            ProcessorAgent.WriteToMemory((ushort)address, value);

            Registers.HL++;
            var counter = Registers.B;
            counter = (byte)(counter - 1);
            Registers.B = counter;
            Registers.ZF = (counter == 0);
            Registers.NF = 1;
            Registers.SF = counter.GetBit(7);
            SetFlags3and5From(counter);

			if(counter != 0) {
				Registers.PC = (ushort)(Registers.PC - 2);
				return 21;
			}

            return 16;
        }

        /// <summary>
        /// The INDR instruction.
        /// </summary>
        byte INDR()
        {
            FetchFinished();

            var portNumber = Registers.C;
            var address = Registers.HL;
            var value = ProcessorAgent.ReadFromPort(portNumber);
            ProcessorAgent.WriteToMemory((ushort)address, value);

            Registers.HL--;
            var counter = Registers.B;
            counter = (byte)(counter - 1);
            Registers.B = counter;
            Registers.ZF = (counter == 0);
            Registers.NF = 1;
            Registers.SF = counter.GetBit(7);
            SetFlags3and5From(counter);

			if(counter != 0) {
				Registers.PC = (ushort)(Registers.PC - 2);
				return 21;
			}

            return 16;
        }

        /// <summary>
        /// The OUTI instruction.
        /// </summary>
        byte OUTI()
        {
            FetchFinished();

            var portNumber = Registers.C;
            var address = Registers.HL;
            var value = ProcessorAgent.ReadFromMemory((ushort)address);
            ProcessorAgent.WriteToPort(portNumber, value);

            Registers.HL++;
            var counter = Registers.B;
            counter = (byte)(counter - 1);
            Registers.B = counter;
            Registers.ZF = (counter == 0);
            Registers.NF = 1;
            Registers.SF = counter.GetBit(7);
            SetFlags3and5From(counter);


            return 16;
        }

        /// <summary>
        /// The OUTD instruction.
        /// </summary>
        byte OUTD()
        {
            FetchFinished();

            var portNumber = Registers.C;
            var address = Registers.HL;
            var value = ProcessorAgent.ReadFromMemory((ushort)address);
            ProcessorAgent.WriteToPort(portNumber, value);

            Registers.HL--;
            var counter = Registers.B;
            counter = (byte)(counter - 1);
            Registers.B = counter;
            Registers.ZF = (counter == 0);
            Registers.NF = 1;
            Registers.SF = counter.GetBit(7);
            SetFlags3and5From(counter);


            return 16;
        }

        /// <summary>
        /// The OTIR instruction.
        /// </summary>
        byte OTIR()
        {
            FetchFinished();

            var portNumber = Registers.C;
            var address = Registers.HL;
            var value = ProcessorAgent.ReadFromMemory((ushort)address);
            ProcessorAgent.WriteToPort(portNumber, value);

            Registers.HL++;
            var counter = Registers.B;
            counter = (byte)(counter - 1);
            Registers.B = counter;
            Registers.ZF = (counter == 0);
            Registers.NF = 1;
            Registers.SF = counter.GetBit(7);
            SetFlags3and5From(counter);

			if(counter != 0) {
				Registers.PC = (ushort)(Registers.PC - 2);
				return 21;
			}

            return 16;
        }

        /// <summary>
        /// The OTDR instruction.
        /// </summary>
        byte OTDR()
        {
            FetchFinished();

            var portNumber = Registers.C;
            var address = Registers.HL;
            var value = ProcessorAgent.ReadFromMemory((ushort)address);
            ProcessorAgent.WriteToPort(portNumber, value);

            Registers.HL--;
            var counter = Registers.B;
            counter = (byte)(counter - 1);
            Registers.B = counter;
            Registers.ZF = (counter == 0);
            Registers.NF = 1;
            Registers.SF = counter.GetBit(7);
            SetFlags3and5From(counter);

			if(counter != 0) {
				Registers.PC = (ushort)(Registers.PC - 2);
				return 21;
			}

            return 16;
        }

    }
}
