// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change LD r,(rr)    .tt instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        /// <summary>
        /// The LD A,(BC) instruction.
        /// </summary>
        byte LD_A_aBC()
        {
		    FetchFinished();
            Registers.A = ProcessorAgent.ReadFromMemory(Registers.BC.ToUShort());
            return 7;
        }

        /// <summary>
        /// The LD A,(DE) instruction.
        /// </summary>
        byte LD_A_aDE()
        {
		    FetchFinished();
            Registers.A = ProcessorAgent.ReadFromMemory(Registers.DE.ToUShort());
            return 7;
        }

        /// <summary>
        /// The LD A,(HL) instruction.
        /// </summary>
        byte LD_A_aHL()
        {
		    FetchFinished();
            Registers.A = ProcessorAgent.ReadFromMemory(Registers.HL.ToUShort());
            return 7;
        }

        /// <summary>
        /// The LD B,(HL) instruction.
        /// </summary>
        byte LD_B_aHL()
        {
		    FetchFinished();
            Registers.B = ProcessorAgent.ReadFromMemory(Registers.HL.ToUShort());
            return 7;
        }

        /// <summary>
        /// The LD C,(HL) instruction.
        /// </summary>
        byte LD_C_aHL()
        {
		    FetchFinished();
            Registers.C = ProcessorAgent.ReadFromMemory(Registers.HL.ToUShort());
            return 7;
        }

        /// <summary>
        /// The LD D,(HL) instruction.
        /// </summary>
        byte LD_D_aHL()
        {
		    FetchFinished();
            Registers.D = ProcessorAgent.ReadFromMemory(Registers.HL.ToUShort());
            return 7;
        }

        /// <summary>
        /// The LD E,(HL) instruction.
        /// </summary>
        byte LD_E_aHL()
        {
		    FetchFinished();
            Registers.E = ProcessorAgent.ReadFromMemory(Registers.HL.ToUShort());
            return 7;
        }

        /// <summary>
        /// The LD H,(HL) instruction.
        /// </summary>
        byte LD_H_aHL()
        {
		    FetchFinished();
            Registers.H = ProcessorAgent.ReadFromMemory(Registers.HL.ToUShort());
            return 7;
        }

        /// <summary>
        /// The LD L,(HL) instruction.
        /// </summary>
        byte LD_L_aHL()
        {
		    FetchFinished();
            Registers.L = ProcessorAgent.ReadFromMemory(Registers.HL.ToUShort());
            return 7;
        }

    }
}
