
// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "LD SP,HL + LD SP,IX + LD SP,IY   .tt" instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        /// <summary>
        /// The LD SP,HL instruction.
        /// </summary>
        byte LD_SP_HL()
        {
            FetchFinished(isLdSp: true);

            Registers.SP = Registers.HL;

            return 6;
        }

        /// <summary>
        /// The LD SP,IX instruction.
        /// </summary>
        byte LD_SP_IX()
        {
            FetchFinished(isLdSp: true);

            Registers.SP = Registers.IX;

            return 10;
        }

        /// <summary>
        /// The LD SP,IY instruction.
        /// </summary>
        byte LD_SP_IY()
        {
            FetchFinished(isLdSp: true);

            Registers.SP = Registers.IY;

            return 10;
        }

    }
}
