
// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "PUSH rr +                   .tt" instead.


namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        /// <summary>
        /// The PUSH AF instruction.
        /// </summary>
        private byte PUSH_AF()
        {
            FetchFinished();

			var valueToPush = Registers.AF;
			var sp = (ushort)(Registers.SP - 1);
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetHighByte());
			sp--;
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetLowByte());
			Registers.SP = (short)sp;

            return 11;
        }

        /// <summary>
        /// The POP AF instruction.
        /// </summary>
        private byte POP_AF()
        {
            FetchFinished();

			var sp = (ushort)Registers.SP;
            var newAF = NumberUtils.CreateShort(
                ProcessorAgent.ReadFromMemory(sp),
                ProcessorAgent.ReadFromMemory((ushort)(sp + 1)));
            Registers.AF = newAF;

            Registers.SP += 2;

            return 10;
        }

        /// <summary>
        /// The PUSH BC instruction.
        /// </summary>
        private byte PUSH_BC()
        {
            FetchFinished();

			var valueToPush = Registers.BC;
			var sp = (ushort)(Registers.SP - 1);
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetHighByte());
			sp--;
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetLowByte());
			Registers.SP = (short)sp;

            return 11;
        }

        /// <summary>
        /// The POP BC instruction.
        /// </summary>
        private byte POP_BC()
        {
            FetchFinished();

			var sp = (ushort)Registers.SP;
            var newBC = NumberUtils.CreateShort(
                ProcessorAgent.ReadFromMemory(sp),
                ProcessorAgent.ReadFromMemory((ushort)(sp + 1)));
            Registers.BC = newBC;

            Registers.SP += 2;

            return 10;
        }

        /// <summary>
        /// The PUSH DE instruction.
        /// </summary>
        private byte PUSH_DE()
        {
            FetchFinished();

			var valueToPush = Registers.DE;
			var sp = (ushort)(Registers.SP - 1);
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetHighByte());
			sp--;
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetLowByte());
			Registers.SP = (short)sp;

            return 11;
        }

        /// <summary>
        /// The POP DE instruction.
        /// </summary>
        private byte POP_DE()
        {
            FetchFinished();

			var sp = (ushort)Registers.SP;
            var newDE = NumberUtils.CreateShort(
                ProcessorAgent.ReadFromMemory(sp),
                ProcessorAgent.ReadFromMemory((ushort)(sp + 1)));
            Registers.DE = newDE;

            Registers.SP += 2;

            return 10;
        }

        /// <summary>
        /// The PUSH HL instruction.
        /// </summary>
        private byte PUSH_HL()
        {
            FetchFinished();

			var valueToPush = Registers.HL;
			var sp = (ushort)(Registers.SP - 1);
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetHighByte());
			sp--;
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetLowByte());
			Registers.SP = (short)sp;

            return 11;
        }

        /// <summary>
        /// The POP HL instruction.
        /// </summary>
        private byte POP_HL()
        {
            FetchFinished();

			var sp = (ushort)Registers.SP;
            var newHL = NumberUtils.CreateShort(
                ProcessorAgent.ReadFromMemory(sp),
                ProcessorAgent.ReadFromMemory((ushort)(sp + 1)));
            Registers.HL = newHL;

            Registers.SP += 2;

            return 10;
        }

        /// <summary>
        /// The PUSH IX instruction.
        /// </summary>
        private byte PUSH_IX()
        {
            FetchFinished();

			var valueToPush = Registers.IX;
			var sp = (ushort)(Registers.SP - 1);
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetHighByte());
			sp--;
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetLowByte());
			Registers.SP = (short)sp;

            return 15;
        }

        /// <summary>
        /// The POP IX instruction.
        /// </summary>
        private byte POP_IX()
        {
            FetchFinished();

			var sp = (ushort)Registers.SP;
            var newIX = NumberUtils.CreateShort(
                ProcessorAgent.ReadFromMemory(sp),
                ProcessorAgent.ReadFromMemory((ushort)(sp + 1)));
            Registers.IX = newIX;

            Registers.SP += 2;

            return 14;
        }

        /// <summary>
        /// The PUSH IY instruction.
        /// </summary>
        private byte PUSH_IY()
        {
            FetchFinished();

			var valueToPush = Registers.IY;
			var sp = (ushort)(Registers.SP - 1);
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetHighByte());
			sp--;
			ProcessorAgent.WriteToMemory(sp, valueToPush.GetLowByte());
			Registers.SP = (short)sp;

            return 15;
        }

        /// <summary>
        /// The POP IY instruction.
        /// </summary>
        private byte POP_IY()
        {
            FetchFinished();

			var sp = (ushort)Registers.SP;
            var newIY = NumberUtils.CreateShort(
                ProcessorAgent.ReadFromMemory(sp),
                ProcessorAgent.ReadFromMemory((ushort)(sp + 1)));
            Registers.IY = newIY;

            Registers.SP += 2;

            return 14;
        }

    }
}