
// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change "RETN            .tt" instead.


namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
		/// <summary>
        /// The RETN instruction.
        /// </summary>
        private byte RETN()
		{
		    FetchFinished(isRet: true);

			var sp = (ushort)Registers.SP;
            var newPC = NumberUtils.CreateShort(
                ProcessorAgent.ReadFromMemory(sp),
                ProcessorAgent.ReadFromMemory((ushort)(sp + 1)));
            Registers.PC = (ushort)newPC;

            Registers.SP += 2;

			Registers.IFF1 = Registers.IFF2;

            return 14;
		}
	}
}