// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change Execute_xD_Instruction.tt instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        private int Execute_DD_Instruction()
        {
            var secondOpcodeByte = ProcessorAgent.PeekNextOpcode();
            
            if(secondOpcodeByte == 0xCB)
            {
                ProcessorAgent.FetchNextOpcode();
                return DDCB_InstructionExecutors[ProcessorAgent.FetchNextOpcode()]();
            }

            if(DD_InstructionExecutors.ContainsKey(secondOpcodeByte)) 
            {
                ProcessorAgent.FetchNextOpcode();
                return DD_InstructionExecutors[secondOpcodeByte]();
            }

            FetchFinished();
            return 4;
        }

        private int Execute_FD_Instruction()
        {
            var secondOpcodeByte = ProcessorAgent.PeekNextOpcode();
            
            if(secondOpcodeByte == 0xCB)
            {
                ProcessorAgent.FetchNextOpcode();
                return FDCB_InstructionExecutors[ProcessorAgent.FetchNextOpcode()]();
            }

            if(FD_InstructionExecutors.ContainsKey(secondOpcodeByte)) 
            {
                ProcessorAgent.FetchNextOpcode();
                return FD_InstructionExecutors[secondOpcodeByte]();
            }

            FetchFinished();
            return 4;
        }

    }
}
