// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change INC rr       .tt instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        /// <summary>
        /// The INC BC instruction.
        /// </summary>
        byte INC_BC()
        {
            FetchFinished();
            MainRegisters.BC = MainRegisters.BC.Inc();
            return 6;
        }

        /// <summary>
        /// The INC DE instruction.
        /// </summary>
        byte INC_DE()
        {
            FetchFinished();
            MainRegisters.DE = MainRegisters.DE.Inc();
            return 6;
        }

        /// <summary>
        /// The INC HL instruction.
        /// </summary>
        byte INC_HL()
        {
            FetchFinished();
            MainRegisters.HL = MainRegisters.HL.Inc();
            return 6;
        }

        /// <summary>
        /// The INC SP instruction.
        /// </summary>
        byte INC_SP()
        {
            FetchFinished();
            Registers.SP = Registers.SP.Inc();
            return 6;
        }

        /// <summary>
        /// The INC IX instruction.
        /// </summary>
        byte INC_IX()
        {
            FetchFinished();
            Registers.IX = Registers.IX.Inc();
            return 10;
        }

        /// <summary>
        /// The INC IY instruction.
        /// </summary>
        byte INC_IY()
        {
            FetchFinished();
            Registers.IY = Registers.IY.Inc();
            return 10;
        }

    }
}
