// AUTOGENERATED CODE
//
// Do not make changes directly to this (.cs) file.
// Change LD r,r       .tt instead.

namespace Konamiman.Z80dotNet
{
    public partial class Z80InstructionExecutor
    {
        /// <summary>
        /// The LD A,A instruction.
        /// </summary>
        byte LD_A_A()
        {
            FetchFinished();

            return 4;
        }

        /// <summary>
        /// The LD B,A instruction.
        /// </summary>
        byte LD_B_A()
        {
            FetchFinished();

            Registers.B = Registers.A;

            return 4;
        }

        /// <summary>
        /// The LD C,A instruction.
        /// </summary>
        byte LD_C_A()
        {
            FetchFinished();

            Registers.C = Registers.A;

            return 4;
        }

        /// <summary>
        /// The LD D,A instruction.
        /// </summary>
        byte LD_D_A()
        {
            FetchFinished();

            Registers.D = Registers.A;

            return 4;
        }

        /// <summary>
        /// The LD E,A instruction.
        /// </summary>
        byte LD_E_A()
        {
            FetchFinished();

            Registers.E = Registers.A;

            return 4;
        }

        /// <summary>
        /// The LD H,A instruction.
        /// </summary>
        byte LD_H_A()
        {
            FetchFinished();

            Registers.H = Registers.A;

            return 4;
        }

        /// <summary>
        /// The LD L,A instruction.
        /// </summary>
        byte LD_L_A()
        {
            FetchFinished();

            Registers.L = Registers.A;

            return 4;
        }

        /// <summary>
        /// The LD A,B instruction.
        /// </summary>
        byte LD_A_B()
        {
            FetchFinished();

            Registers.A = Registers.B;

            return 4;
        }

        /// <summary>
        /// The LD B,B instruction.
        /// </summary>
        byte LD_B_B()
        {
            FetchFinished();

            return 4;
        }

        /// <summary>
        /// The LD C,B instruction.
        /// </summary>
        byte LD_C_B()
        {
            FetchFinished();

            Registers.C = Registers.B;

            return 4;
        }

        /// <summary>
        /// The LD D,B instruction.
        /// </summary>
        byte LD_D_B()
        {
            FetchFinished();

            Registers.D = Registers.B;

            return 4;
        }

        /// <summary>
        /// The LD E,B instruction.
        /// </summary>
        byte LD_E_B()
        {
            FetchFinished();

            Registers.E = Registers.B;

            return 4;
        }

        /// <summary>
        /// The LD H,B instruction.
        /// </summary>
        byte LD_H_B()
        {
            FetchFinished();

            Registers.H = Registers.B;

            return 4;
        }

        /// <summary>
        /// The LD L,B instruction.
        /// </summary>
        byte LD_L_B()
        {
            FetchFinished();

            Registers.L = Registers.B;

            return 4;
        }

        /// <summary>
        /// The LD A,C instruction.
        /// </summary>
        byte LD_A_C()
        {
            FetchFinished();

            Registers.A = Registers.C;

            return 4;
        }

        /// <summary>
        /// The LD B,C instruction.
        /// </summary>
        byte LD_B_C()
        {
            FetchFinished();

            Registers.B = Registers.C;

            return 4;
        }

        /// <summary>
        /// The LD C,C instruction.
        /// </summary>
        byte LD_C_C()
        {
            FetchFinished();

            return 4;
        }

        /// <summary>
        /// The LD D,C instruction.
        /// </summary>
        byte LD_D_C()
        {
            FetchFinished();

            Registers.D = Registers.C;

            return 4;
        }

        /// <summary>
        /// The LD E,C instruction.
        /// </summary>
        byte LD_E_C()
        {
            FetchFinished();

            Registers.E = Registers.C;

            return 4;
        }

        /// <summary>
        /// The LD H,C instruction.
        /// </summary>
        byte LD_H_C()
        {
            FetchFinished();

            Registers.H = Registers.C;

            return 4;
        }

        /// <summary>
        /// The LD L,C instruction.
        /// </summary>
        byte LD_L_C()
        {
            FetchFinished();

            Registers.L = Registers.C;

            return 4;
        }

        /// <summary>
        /// The LD A,D instruction.
        /// </summary>
        byte LD_A_D()
        {
            FetchFinished();

            Registers.A = Registers.D;

            return 4;
        }

        /// <summary>
        /// The LD B,D instruction.
        /// </summary>
        byte LD_B_D()
        {
            FetchFinished();

            Registers.B = Registers.D;

            return 4;
        }

        /// <summary>
        /// The LD C,D instruction.
        /// </summary>
        byte LD_C_D()
        {
            FetchFinished();

            Registers.C = Registers.D;

            return 4;
        }

        /// <summary>
        /// The LD D,D instruction.
        /// </summary>
        byte LD_D_D()
        {
            FetchFinished();

            return 4;
        }

        /// <summary>
        /// The LD E,D instruction.
        /// </summary>
        byte LD_E_D()
        {
            FetchFinished();

            Registers.E = Registers.D;

            return 4;
        }

        /// <summary>
        /// The LD H,D instruction.
        /// </summary>
        byte LD_H_D()
        {
            FetchFinished();

            Registers.H = Registers.D;

            return 4;
        }

        /// <summary>
        /// The LD L,D instruction.
        /// </summary>
        byte LD_L_D()
        {
            FetchFinished();

            Registers.L = Registers.D;

            return 4;
        }

        /// <summary>
        /// The LD A,E instruction.
        /// </summary>
        byte LD_A_E()
        {
            FetchFinished();

            Registers.A = Registers.E;

            return 4;
        }

        /// <summary>
        /// The LD B,E instruction.
        /// </summary>
        byte LD_B_E()
        {
            FetchFinished();

            Registers.B = Registers.E;

            return 4;
        }

        /// <summary>
        /// The LD C,E instruction.
        /// </summary>
        byte LD_C_E()
        {
            FetchFinished();

            Registers.C = Registers.E;

            return 4;
        }

        /// <summary>
        /// The LD D,E instruction.
        /// </summary>
        byte LD_D_E()
        {
            FetchFinished();

            Registers.D = Registers.E;

            return 4;
        }

        /// <summary>
        /// The LD E,E instruction.
        /// </summary>
        byte LD_E_E()
        {
            FetchFinished();

            return 4;
        }

        /// <summary>
        /// The LD H,E instruction.
        /// </summary>
        byte LD_H_E()
        {
            FetchFinished();

            Registers.H = Registers.E;

            return 4;
        }

        /// <summary>
        /// The LD L,E instruction.
        /// </summary>
        byte LD_L_E()
        {
            FetchFinished();

            Registers.L = Registers.E;

            return 4;
        }

        /// <summary>
        /// The LD A,H instruction.
        /// </summary>
        byte LD_A_H()
        {
            FetchFinished();

            Registers.A = Registers.H;

            return 4;
        }

        /// <summary>
        /// The LD B,H instruction.
        /// </summary>
        byte LD_B_H()
        {
            FetchFinished();

            Registers.B = Registers.H;

            return 4;
        }

        /// <summary>
        /// The LD C,H instruction.
        /// </summary>
        byte LD_C_H()
        {
            FetchFinished();

            Registers.C = Registers.H;

            return 4;
        }

        /// <summary>
        /// The LD D,H instruction.
        /// </summary>
        byte LD_D_H()
        {
            FetchFinished();

            Registers.D = Registers.H;

            return 4;
        }

        /// <summary>
        /// The LD E,H instruction.
        /// </summary>
        byte LD_E_H()
        {
            FetchFinished();

            Registers.E = Registers.H;

            return 4;
        }

        /// <summary>
        /// The LD H,H instruction.
        /// </summary>
        byte LD_H_H()
        {
            FetchFinished();

            return 4;
        }

        /// <summary>
        /// The LD L,H instruction.
        /// </summary>
        byte LD_L_H()
        {
            FetchFinished();

            Registers.L = Registers.H;

            return 4;
        }

        /// <summary>
        /// The LD A,L instruction.
        /// </summary>
        byte LD_A_L()
        {
            FetchFinished();

            Registers.A = Registers.L;

            return 4;
        }

        /// <summary>
        /// The LD B,L instruction.
        /// </summary>
        byte LD_B_L()
        {
            FetchFinished();

            Registers.B = Registers.L;

            return 4;
        }

        /// <summary>
        /// The LD C,L instruction.
        /// </summary>
        byte LD_C_L()
        {
            FetchFinished();

            Registers.C = Registers.L;

            return 4;
        }

        /// <summary>
        /// The LD D,L instruction.
        /// </summary>
        byte LD_D_L()
        {
            FetchFinished();

            Registers.D = Registers.L;

            return 4;
        }

        /// <summary>
        /// The LD E,L instruction.
        /// </summary>
        byte LD_E_L()
        {
            FetchFinished();

            Registers.E = Registers.L;

            return 4;
        }

        /// <summary>
        /// The LD H,L instruction.
        /// </summary>
        byte LD_H_L()
        {
            FetchFinished();

            Registers.H = Registers.L;

            return 4;
        }

        /// <summary>
        /// The LD L,L instruction.
        /// </summary>
        byte LD_L_L()
        {
            FetchFinished();

            return 4;
        }

    }
}
